language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.4.1

install:
 - pip install -r requirements.txt
 - pip install coverage

script:
 -  coverage run manage.py test

after_script:
 - pip install -q coveralls
 - coveralls

email:
    recipients:
    - el_moi@ciencias.unam.mx
    on_success: always
    on_failure: always
